# Generated by Django 2.2.4 on 2019-11-13 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 13, 34, 46, 623449, tzinfo=utc), verbose_name='录入时间'),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=200, verbose_name='试卷标题')),
                ('paper_score', models.IntegerField(verbose_name='试卷分数')),
                ('paper_exam_time', models.IntegerField(verbose_name='考试时间')),
                ('paper_author', models.CharField(blank=True, max_length=20, verbose_name='出题人')),
                ('exam_time', models.DateTimeField(verbose_name='考试时间')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('paper_question', models.ManyToManyField(related_name='试卷题目', to='manage_examination.Question')),
                ('paper_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_examination.Subject', verbose_name='考试科目')),
            ],
            options={
                'verbose_name': '试卷',
            },
        ),
    ]
