# Generated by Django 2.2.4 on 2019-11-17 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_examination', '0002_auto_20191113_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=1000, verbose_name='题目标题'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 16, 52, 13, 832547, tzinfo=utc), verbose_name='录入时间'),
        ),
    ]
