# Generated by Django 2.2.7 on 2019-12-10 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_examination', '0003_auto_20191118_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_text', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签集',
            },
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 14, 42, 33, 77042, tzinfo=utc), verbose_name='录入时间'),
        ),
        migrations.AddField(
            model_name='question',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='标签', to='manage_examination.Label'),
        ),
    ]
