# Generated by Django 2.2.7 on 2019-12-27 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_examination', '0004_auto_20191210_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='exam_time',
            field=models.DateTimeField(blank=True, verbose_name='考试时间'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 3, 41, 28, 252372, tzinfo=utc), verbose_name='录入时间'),
        ),
    ]
